package views;

import models.Tweet;

public class TweetPanel extends javax.swing.JPanel {

  public TweetPanel(Tweet tweet) {
    initComponents();
    
    lbName.setText(tweet.getName());
    lbUser.setText(tweet.getUser());
    lbCreatedAt.setText(tweet.getCreatedAt());
    jtaContent.setText(tweet.getContent());
    lbComment.setText("Comment:" + tweet.getComment());
    lbRetweet.setText("Retweet:" + tweet.getRetweet());
    lbLike.setText("Like:" + tweet.getLike());
    lbView.setText("View:" + tweet.getView());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jtaContent = new javax.swing.JTextArea();
    jPanel1 = new javax.swing.JPanel();
    lbName = new javax.swing.JLabel();
    lbUser = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    lbComment = new javax.swing.JLabel();
    lbRetweet = new javax.swing.JLabel();
    lbLike = new javax.swing.JLabel();
    lbView = new javax.swing.JLabel();
    lbCreatedAt = new javax.swing.JLabel();

    setBackground(new java.awt.Color(204, 255, 255));
    setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jtaContent.setColumns(20);
    jtaContent.setLineWrap(true);
    jtaContent.setRows(5);
    jScrollPane1.setViewportView(jtaContent);

    jPanel1.setBackground(new java.awt.Color(255, 255, 204));

    lbName.setText("name");

    lbUser.setText("username");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lbName)
        .addGap(29, 29, 29)
        .addComponent(lbUser)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(9, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbName)
          .addComponent(lbUser))
        .addContainerGap())
    );

    jPanel2.setBackground(new java.awt.Color(204, 255, 204));

    lbComment.setText("Comment");

    lbRetweet.setText("Retweet");

    lbLike.setText("Like");

    lbView.setText("View");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lbComment)
        .addGap(44, 44, 44)
        .addComponent(lbRetweet)
        .addGap(50, 50, 50)
        .addComponent(lbLike)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(lbView)
        .addGap(35, 35, 35))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbComment)
          .addComponent(lbRetweet)
          .addComponent(lbLike)
          .addComponent(lbView))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    lbCreatedAt.setText("Created at");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lbCreatedAt)
            .addGap(0, 307, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lbCreatedAt)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jtaContent;
  private javax.swing.JLabel lbComment;
  private javax.swing.JLabel lbCreatedAt;
  private javax.swing.JLabel lbLike;
  private javax.swing.JLabel lbName;
  private javax.swing.JLabel lbRetweet;
  private javax.swing.JLabel lbUser;
  private javax.swing.JLabel lbView;
  // End of variables declaration//GEN-END:variables
}
